### ISSUE TITLE
localhost change in makefile

### ISSUE THREAD

**Issue by joeblew99** [mlctrez/go-nats-app#1]
I had to change this:

```sh
@DEV=1 ADDRESS=10.0.0.41:9021 ./temp/$(APP_NAME)
```

to

```sh 
 @DEV=1 ADDRESS=0.0.0.0:9021 ./temp/$(APP_NAME)
```

**Comment by mlctrez** [comment]
This is fixed.. I removed the ADDRESS environment variable completely. Now the default is localhost:8080.  Must have left this in for testing at some point.

**Comment by gedw99** [comment]
Cheers :)
